### ISSUE TITLE
Social Auth Support?

### ISSUE THREAD

**Issue by rjayako** [jakemmarsh/expressed-boilerplate#1]
Hello, can we have social auth support? if possible via Passport can you update the readme with instructions?

**Comment by jakemmarsh** [comment]
Multiple social auth flows are supported and documented by Passport: [docs here](http://passportjs.org/docs)
- [Facebook](http://passportjs.org/docs/facebook)
- [Twitter](http://passportjs.org/docs/twitter)
- [Google](http://passportjs.org/docs/google)

I'm not sure if I'll add these to the boilerplate readme since they're already fully documented in the above links, but I'll consider it (or at least add links)
